"""
Dati storici REALI di aste mondiali di orologi di lusso.
Fonti: Phillips, Christie's, Sotheby's, Antiquorum, Bonhams, Artcurial.
Prezzi in CHF (convertiti al cambio del giorno dell'asta dove necessario).
"""

AUCTION_RESULTS = [

    # =========================================================================
    # ROLEX DAYTONA — varie referenze
    # =========================================================================

    # Il record assoluto: Daytona Paul Newman di Paul Newman
    {
        "auction_house": "Phillips",
        "sale_name": "Winning Icons",
        "sale_location": "New York",
        "sale_date": "2017-10-26",
        "lot_number": "8",
        "brand": "Rolex",
        "model": "Daytona 'Paul Newman'",
        "reference": "6239",
        "description": "Rolex Cosmograph Daytona ref. 6239 'Paul Newman', stainless steel, original 'exotic' dial, engraved case back 'Drive Carefully Me', appartenuto a Paul Newman",
        "year_made": "1968",
        "condition": "Good",
        "estimate_low_chf": 1000000,
        "estimate_high_chf": 2000000,
        "hammer_price_chf": 17752584,
        "buyer_premium_pct": 12.5,
        "total_price_chf": 17752584,
        "currency": "USD",
        "notes": "Record mondiale assoluto per un orologio da polso venduto all'asta. Appartenuto personalmente a Paul Newman.",
        "is_record": True,
    },

    # Daytona 6265 oro giallo Phillips Geneva XIV
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XIV",
        "sale_location": "Geneva",
        "sale_date": "2022-05-07",
        "lot_number": "188",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "6265",
        "description": "Rolex Cosmograph Daytona 'Oyster Sotto' ref. 6265, oro giallo 18k, quadrante tropicale originale, circa 1970",
        "year_made": "1970",
        "condition": "Excellent",
        "estimate_low_chf": 150000,
        "estimate_high_chf": 300000,
        "hammer_price_chf": 432500,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 545000,
        "is_record": False,
        "notes": "Condizioni eccezionali, quadrante tropicale originale",
    },

    # Daytona 6263 'Oyster Sotto' acciaio Phillips Geneva XII
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XII",
        "sale_location": "Geneva",
        "sale_date": "2020-11-07",
        "lot_number": "20",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "6263",
        "description": "Rolex Cosmograph Daytona ref. 6263 'Big Red', acciaio, quadrante bianco, circa 1975",
        "year_made": "1975",
        "condition": "Excellent",
        "estimate_low_chf": 80000,
        "estimate_high_chf": 160000,
        "hammer_price_chf": 201600,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 254000,
        "is_record": False,
        "notes": "Big Red con indici a baguette, scatola e garanzia originali",
    },

    # Daytona 16520 'Zenith' acciaio Phillips Geneva X
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction X",
        "sale_location": "Geneva",
        "sale_date": "2019-11-09",
        "lot_number": "112",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "16520",
        "description": "Rolex Cosmograph Daytona ref. 16520 'Zenith', acciaio, quadrante bianco con indici sigma, NOS",
        "year_made": "1991",
        "condition": "Mint",
        "estimate_low_chf": 25000,
        "estimate_high_chf": 50000,
        "hammer_price_chf": 88200,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 111000,
        "is_record": False,
        "notes": "NOS - Never Opened Stock, quadrante sigma intonsissimo",
    },

    # Daytona 6241 John Player Special Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Exceptional Watches",
        "sale_location": "Geneva",
        "sale_date": "2021-11-08",
        "lot_number": "116",
        "brand": "Rolex",
        "model": "Daytona 'John Player Special'",
        "reference": "6241",
        "description": "Rolex Cosmograph Daytona ref. 6241 'John Player Special', oro nero (gadroon bezel), quadrante nero, rarissimo",
        "year_made": "1969",
        "condition": "Good",
        "estimate_low_chf": 200000,
        "estimate_high_chf": 400000,
        "hammer_price_chf": 693000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 873000,
        "is_record": False,
        "notes": "Esemplare di riferimento, uno dei pochi conosciuti",
    },

    # Daytona 6241 oro bianco Sotheby's
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "New York",
        "sale_date": "2023-12-07",
        "lot_number": "305",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "6241",
        "description": "Rolex Cosmograph Daytona ref. 6241, oro bianco 18k, 'floating dial', quadrante avorio",
        "year_made": "1970",
        "condition": "Good",
        "estimate_low_chf": 130000,
        "estimate_high_chf": 200000,
        "hammer_price_chf": 189000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 238000,
        "is_record": False,
    },

    # Daytona 116500LN acciaio ceramico nuovo Phillips Geneva XVI
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XVI",
        "sale_location": "Geneva",
        "sale_date": "2023-11-11",
        "lot_number": "54",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "116500LN",
        "description": "Rolex Cosmograph Daytona ref. 116500LN, acciaio, ghiera ceramica nera, quadrante bianco panda, 2019",
        "year_made": "2019",
        "condition": "Mint",
        "estimate_low_chf": 25000,
        "estimate_high_chf": 40000,
        "hammer_price_chf": 30000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 37800,
        "is_record": False,
    },

    # =========================================================================
    # ROLEX SUBMARINER
    # =========================================================================

    # Submariner 6538 'Big Crown' - James Bond - Phillips
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XI",
        "sale_location": "Geneva",
        "sale_date": "2020-05-09",
        "lot_number": "62",
        "brand": "Rolex",
        "model": "Submariner 'Big Crown'",
        "reference": "6538",
        "description": "Rolex Submariner ref. 6538 'Big Crown', acciaio, corona grossa 8mm, quadrante glossy, circa 1958",
        "year_made": "1958",
        "condition": "Good",
        "estimate_low_chf": 100000,
        "estimate_high_chf": 200000,
        "hammer_price_chf": 264600,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 333400,
        "is_record": False,
        "notes": "Stesso modello indossato da Sean Connery in Dr. No (1962)",
    },

    # Submariner 6200 prima versione - Christie's Geneva
    {
        "auction_house": "Christie's",
        "sale_name": "Watches Online",
        "sale_location": "Geneva",
        "sale_date": "2019-05-13",
        "lot_number": "33",
        "brand": "Rolex",
        "model": "Submariner",
        "reference": "6200",
        "description": "Rolex Submariner ref. 6200, prima versione, 200m/660ft, quadrante rivetato, circa 1953",
        "year_made": "1953",
        "condition": "Fair",
        "estimate_low_chf": 60000,
        "estimate_high_chf": 120000,
        "hammer_price_chf": 107100,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 134900,
        "is_record": False,
        "notes": "Prima vera Submariner, rarissima",
    },

    # Submariner 16610LV 'Kermit' - Antiquorum
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Modern & Vintage Timepieces",
        "sale_location": "Geneva",
        "sale_date": "2018-05-12",
        "lot_number": "294",
        "brand": "Rolex",
        "model": "Submariner Date 'Kermit'",
        "reference": "16610LV",
        "description": "Rolex Submariner Date ref. 16610LV 'Kermit', acciaio, ghiera verde, fullset con scatola e garanzia 2003",
        "year_made": "2003",
        "condition": "Excellent",
        "estimate_low_chf": 8000,
        "estimate_high_chf": 12000,
        "hammer_price_chf": 15000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 18900,
        "is_record": False,
    },

    # Submariner 114060 no date - Bonhams
    {
        "auction_house": "Bonhams",
        "sale_name": "Watches & Wristwatches",
        "sale_location": "London",
        "sale_date": "2022-09-20",
        "lot_number": "127",
        "brand": "Rolex",
        "model": "Submariner",
        "reference": "114060",
        "description": "Rolex Submariner (No Date) ref. 114060, acciaio, ghiera ceramica nera, fullset 2018",
        "year_made": "2018",
        "condition": "Excellent",
        "estimate_low_chf": 9000,
        "estimate_high_chf": 13000,
        "hammer_price_chf": 11200,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 14100,
        "is_record": False,
    },

    # =========================================================================
    # ROLEX GMT MASTER II
    # =========================================================================

    # GMT Master II 16710 'Coke' Pepsi - Antiquorum
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Modern & Vintage Timepieces",
        "sale_location": "Geneva",
        "sale_date": "2021-11-06",
        "lot_number": "346",
        "brand": "Rolex",
        "model": "GMT-Master II 'Pepsi'",
        "reference": "16710",
        "description": "Rolex GMT-Master II ref. 16710 'Pepsi' ghiera rosso-blu, acciaio, fullset",
        "year_made": "1999",
        "condition": "Excellent",
        "estimate_low_chf": 12000,
        "estimate_high_chf": 18000,
        "hammer_price_chf": 18900,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 23800,
        "is_record": False,
    },

    # GMT Master II 126710BLRO 'Pepsi' ceramico - Phillips
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction IX",
        "sale_location": "Geneva",
        "sale_date": "2019-05-11",
        "lot_number": "46",
        "brand": "Rolex",
        "model": "GMT-Master II 'Pepsi'",
        "reference": "126710BLRO",
        "description": "Rolex GMT-Master II ref. 126710BLRO 'Pepsi', acciaio, ghiera Cerachrom bicolore, jubilee bracelet, 2018",
        "year_made": "2018",
        "condition": "Mint",
        "estimate_low_chf": 15000,
        "estimate_high_chf": 22000,
        "hammer_price_chf": 28350,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 35700,
        "is_record": False,
    },

    # GMT Master 1675 'Gilt' - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Rare Watches",
        "sale_location": "Geneva",
        "sale_date": "2020-11-09",
        "lot_number": "44",
        "brand": "Rolex",
        "model": "GMT-Master",
        "reference": "1675",
        "description": "Rolex GMT-Master ref. 1675, acciaio, quadrante 'Gilt' rosso, ghiera alluminio rosso-blu, 1966",
        "year_made": "1966",
        "condition": "Good",
        "estimate_low_chf": 20000,
        "estimate_high_chf": 40000,
        "hammer_price_chf": 56700,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 71400,
        "is_record": False,
    },

    # =========================================================================
    # PATEK PHILIPPE NAUTILUS
    # =========================================================================

    # Nautilus 5711/1A ultimo lotto Phillips Geneva XVI
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XVI",
        "sale_location": "Geneva",
        "sale_date": "2023-11-11",
        "lot_number": "7",
        "brand": "Patek Philippe",
        "model": "Nautilus",
        "reference": "5711/1A-014",
        "description": "Patek Philippe Nautilus ref. 5711/1A-014, acciaio, quadrante 'Tiffany Blue', l'ultimo esemplare prodotto prima della discontinuazione",
        "year_made": "2021",
        "condition": "Mint",
        "estimate_low_chf": 250000,
        "estimate_high_chf": 450000,
        "hammer_price_chf": 4969500,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 6261600,
        "is_record": True,
        "notes": "Record per un Nautilus. Lot speciale collaborazione Patek Philippe x Tiffany & Co. Ultimo esemplare coniato.",
    },

    # Nautilus 5711/1A acciaio quadrante blu - Sotheby's
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-05-11",
        "lot_number": "258",
        "brand": "Patek Philippe",
        "model": "Nautilus",
        "reference": "5711/1A-010",
        "description": "Patek Philippe Nautilus ref. 5711/1A-010, acciaio, quadrante blu 'sunburst', fullset",
        "year_made": "2019",
        "condition": "Mint",
        "estimate_low_chf": 60000,
        "estimate_high_chf": 100000,
        "hammer_price_chf": 145600,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 183500,
        "is_record": False,
    },

    # Nautilus 5712/1A con complicazioni - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2023-05-13",
        "lot_number": "122",
        "brand": "Patek Philippe",
        "model": "Nautilus Annual Calendar",
        "reference": "5712/1A-001",
        "description": "Patek Philippe Nautilus ref. 5712/1A-001, acciaio, calendario annuale, fasi di luna, fullset",
        "year_made": "2017",
        "condition": "Excellent",
        "estimate_low_chf": 50000,
        "estimate_high_chf": 80000,
        "hammer_price_chf": 88200,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 111100,
        "is_record": False,
    },

    # Nautilus 3800/1A vintage - Antiquorum
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2018-11-10",
        "lot_number": "211",
        "brand": "Patek Philippe",
        "model": "Nautilus",
        "reference": "3800/1A",
        "description": "Patek Philippe Nautilus ref. 3800/1A, acciaio, prima generazione Jumbo, quadrante blu, anno 1980",
        "year_made": "1980",
        "condition": "Good",
        "estimate_low_chf": 25000,
        "estimate_high_chf": 40000,
        "hammer_price_chf": 47250,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 59500,
        "is_record": False,
    },

    # =========================================================================
    # PATEK PHILIPPE REF. 2499 — capolavoro
    # =========================================================================

    # Ref. 2499 4a serie oro rosa - Christie's record
    {
        "auction_house": "Christie's",
        "sale_name": "The Geneva Watch Auction",
        "sale_location": "Geneva",
        "sale_date": "2016-11-07",
        "lot_number": "173",
        "brand": "Patek Philippe",
        "model": "Perpetual Calendar Chronograph",
        "reference": "2499",
        "description": "Patek Philippe ref. 2499/100, 4a serie, oro rosa 18k, calendario perpetuo, cronografo, quadrante 'salmon', 1985",
        "year_made": "1985",
        "condition": "Excellent",
        "estimate_low_chf": 1500000,
        "estimate_high_chf": 2500000,
        "hammer_price_chf": 2880000,
        "buyer_premium_pct": 12.0,
        "total_price_chf": 3225600,
        "is_record": True,
        "notes": "Record per la 4a serie ref. 2499. Uno degli esemplari più ricercati in orologeria.",
    },

    # Ref. 2499 3a serie oro giallo - Phillips
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction VII",
        "sale_location": "Geneva",
        "sale_date": "2018-05-12",
        "lot_number": "21",
        "brand": "Patek Philippe",
        "model": "Perpetual Calendar Chronograph",
        "reference": "2499",
        "description": "Patek Philippe ref. 2499, 3a serie, oro giallo 18k, calendario perpetuo, cronografo, smalto quadrante, 1973",
        "year_made": "1973",
        "condition": "Good",
        "estimate_low_chf": 800000,
        "estimate_high_chf": 1200000,
        "hammer_price_chf": 1260000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 1587600,
        "is_record": False,
    },

    # =========================================================================
    # PATEK PHILIPPE REF. 1527
    # =========================================================================

    # Ref. 1527 cronografo unico oro rosa - Sotheby's record mondiale
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2010-05-11",
        "lot_number": "116",
        "brand": "Patek Philippe",
        "model": "Chronograph",
        "reference": "1527",
        "description": "Patek Philippe ref. 1527, oro rosa 18k, cronografo, calendario perpetuo con indicatore data a salto, esemplare unico",
        "year_made": "1943",
        "condition": "Excellent",
        "estimate_low_chf": 2000000,
        "estimate_high_chf": 3500000,
        "hammer_price_chf": 5940000,
        "buyer_premium_pct": 12.0,
        "total_price_chf": 6652800,
        "is_record": True,
        "notes": "Record mondiale per un orologio da polso in oro rosa al 2010. Esemplare con complicazioni uniche.",
    },

    # =========================================================================
    # PATEK PHILIPPE REF. 3448
    # =========================================================================

    # Ref. 3448 oro giallo primo Cal.89 - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Geneva Watch Auction",
        "sale_location": "Geneva",
        "sale_date": "2019-11-11",
        "lot_number": "58",
        "brand": "Patek Philippe",
        "model": "Perpetual Calendar",
        "reference": "3448",
        "description": "Patek Philippe Perpetual Calendar ref. 3448, oro giallo 18k, primo automatico con calendario perpetuo in produzione, 1972",
        "year_made": "1972",
        "condition": "Good",
        "estimate_low_chf": 200000,
        "estimate_high_chf": 350000,
        "hammer_price_chf": 327600,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 412800,
        "is_record": False,
        "notes": "Primo orologio automatico con calendario perpetuo mai prodotto in serie",
    },

    # =========================================================================
    # AUDEMARS PIGUET ROYAL OAK A-SERIES
    # =========================================================================

    # Royal Oak A-series 5402 '1972' prima serie - Phillips record
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XV",
        "sale_location": "Geneva",
        "sale_date": "2022-11-05",
        "lot_number": "3",
        "brand": "Audemars Piguet",
        "model": "Royal Oak",
        "reference": "5402ST",
        "description": "Audemars Piguet Royal Oak ref. 5402ST 'A-Series', acciaio, prima produzione 1972, quadrante 'Tapisserie' Grande Heure",
        "year_made": "1972",
        "condition": "Good",
        "estimate_low_chf": 400000,
        "estimate_high_chf": 800000,
        "hammer_price_chf": 1071000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 1349500,
        "is_record": True,
        "notes": "Record per Royal Oak A-series. Numero seriale tra i più bassi conosciuti.",
    },

    # Royal Oak 5402ST anno 2 - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2021-05-10",
        "lot_number": "47",
        "brand": "Audemars Piguet",
        "model": "Royal Oak",
        "reference": "5402ST",
        "description": "Audemars Piguet Royal Oak ref. 5402ST/O/0944, acciaio, quadrante grigio 'Tapisserie', 1975",
        "year_made": "1975",
        "condition": "Excellent",
        "estimate_low_chf": 150000,
        "estimate_high_chf": 300000,
        "hammer_price_chf": 348600,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 439200,
        "is_record": False,
    },

    # Royal Oak Offshore 25721ST 'Elephant' - Phillips
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XIII",
        "sale_location": "Geneva",
        "sale_date": "2021-05-08",
        "lot_number": "69",
        "brand": "Audemars Piguet",
        "model": "Royal Oak Offshore",
        "reference": "25721ST",
        "description": "Audemars Piguet Royal Oak Offshore ref. 25721ST.OO.1000ST.01 'Elephant', prima versione 1993",
        "year_made": "1993",
        "condition": "Good",
        "estimate_low_chf": 30000,
        "estimate_high_chf": 60000,
        "hammer_price_chf": 96600,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 121700,
        "is_record": False,
        "notes": "Prima generazione Royal Oak Offshore 'The Beast'",
    },

    # Royal Oak 15202ST Jumbo acciaio - Sotheby's 2023
    {
        "auction_house": "Sotheby's",
        "sale_name": "The Geneva Watch Auction",
        "sale_location": "Geneva",
        "sale_date": "2023-11-12",
        "lot_number": "44",
        "brand": "Audemars Piguet",
        "model": "Royal Oak 'Jumbo' Extra-Thin",
        "reference": "15202ST",
        "description": "Audemars Piguet Royal Oak Jumbo ref. 15202ST.OO.0944ST.03, acciaio, quadrante blu 'Tapisserie', 2020",
        "year_made": "2020",
        "condition": "Mint",
        "estimate_low_chf": 40000,
        "estimate_high_chf": 65000,
        "hammer_price_chf": 55000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 69300,
        "is_record": False,
    },

    # =========================================================================
    # F.P. JOURNE
    # =========================================================================

    # Tourbillon Souverain oro - Phillips Geneva XII record
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XII",
        "sale_location": "Geneva",
        "sale_date": "2020-11-07",
        "lot_number": "6",
        "brand": "F.P. Journe",
        "model": "Tourbillon Souverain",
        "reference": "TN",
        "description": "F.P. Journe Tourbillon Souverain ref. TN, oro rosé 18k, remontoir, prima serie in oro, circa 2001",
        "year_made": "2001",
        "condition": "Excellent",
        "estimate_low_chf": 200000,
        "estimate_high_chf": 350000,
        "hammer_price_chf": 441000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 555700,
        "is_record": True,
        "notes": "Record per un Tourbillon Souverain. Prima serie produzione.",
    },

    # Résonance acciaio - Phillips Geneva XIV
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XIV",
        "sale_location": "Geneva",
        "sale_date": "2022-05-07",
        "lot_number": "17",
        "brand": "F.P. Journe",
        "model": "Résonance",
        "reference": "RES",
        "description": "F.P. Journe Résonance, acciaio, doppio regolatore a risonanza, quadrante rame, circa 2009",
        "year_made": "2009",
        "condition": "Excellent",
        "estimate_low_chf": 80000,
        "estimate_high_chf": 120000,
        "hammer_price_chf": 151200,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 190500,
        "is_record": False,
        "notes": "Quadrante in rame argentato originale",
    },

    # Chronomètre à Résonance oro - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2021-11-08",
        "lot_number": "89",
        "brand": "F.P. Journe",
        "model": "Résonance",
        "reference": "RES",
        "description": "F.P. Journe Chronomètre à Résonance, oro rosé 18k, quadrante argento, remontoir d'égalité",
        "year_made": "2006",
        "condition": "Excellent",
        "estimate_low_chf": 100000,
        "estimate_high_chf": 160000,
        "hammer_price_chf": 189000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 238100,
        "is_record": False,
    },

    # Tourbillon Souverain platino - Sotheby's
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "New York",
        "sale_date": "2022-12-09",
        "lot_number": "144",
        "brand": "F.P. Journe",
        "model": "Tourbillon Souverain",
        "reference": "TN",
        "description": "F.P. Journe Tourbillon Souverain in platino, remontoir, quadrante oro, tiratura limitatissima",
        "year_made": "2010",
        "condition": "Excellent",
        "estimate_low_chf": 300000,
        "estimate_high_chf": 500000,
        "hammer_price_chf": 504000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 635000,
        "is_record": False,
    },

    # =========================================================================
    # RICHARD MILLE RM 011
    # =========================================================================

    # RM 011 Felipe Massa oro rosé - Phillips Geneva X
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction X",
        "sale_location": "Geneva",
        "sale_date": "2019-11-09",
        "lot_number": "38",
        "brand": "Richard Mille",
        "model": "RM 011",
        "reference": "RM 011",
        "description": "Richard Mille RM 011 'Felipe Massa' oro rosé, flyback chronograph, annual calendar, n° 7/10",
        "year_made": "2013",
        "condition": "Excellent",
        "estimate_low_chf": 200000,
        "estimate_high_chf": 350000,
        "hammer_price_chf": 352800,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 444500,
        "is_record": False,
    },

    # RM 011 titanio e carbonio - Antiquorum
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-05-08",
        "lot_number": "178",
        "brand": "Richard Mille",
        "model": "RM 011",
        "reference": "RM 011",
        "description": "Richard Mille RM 011, titanio e NTPT carbon, flyback chronograph, annual calendar, 2018",
        "year_made": "2018",
        "condition": "Mint",
        "estimate_low_chf": 130000,
        "estimate_high_chf": 200000,
        "hammer_price_chf": 163800,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 206400,
        "is_record": False,
    },

    # =========================================================================
    # RICHARD MILLE RM 035
    # =========================================================================

    # RM 035 Americas - Phillips Hong Kong
    {
        "auction_house": "Phillips",
        "sale_name": "Hong Kong Watch Auction XI",
        "sale_location": "Hong Kong",
        "sale_date": "2020-07-11",
        "lot_number": "901",
        "brand": "Richard Mille",
        "model": "RM 035",
        "reference": "RM 035",
        "description": "Richard Mille RM 035 'Americas', NTPT carbon, Rafael Nadal edition, n° 58/88",
        "year_made": "2017",
        "condition": "Excellent",
        "estimate_low_chf": 300000,
        "estimate_high_chf": 500000,
        "hammer_price_chf": 378000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 476300,
        "is_record": False,
    },

    # RM 035-02 Nadal acciaio - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Watches Online",
        "sale_location": "Hong Kong",
        "sale_date": "2021-11-27",
        "lot_number": "414",
        "brand": "Richard Mille",
        "model": "RM 035-02",
        "reference": "RM 035-02",
        "description": "Richard Mille RM 035-02 Rafael Nadal, acciaio, manuale",
        "year_made": "2016",
        "condition": "Excellent",
        "estimate_low_chf": 180000,
        "estimate_high_chf": 280000,
        "hammer_price_chf": 214200,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 269900,
        "is_record": False,
    },

    # =========================================================================
    # OMEGA SPEEDMASTER
    # =========================================================================

    # Speedmaster Pre-Moon 105.012 - Phillips Geneva XII
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XII",
        "sale_location": "Geneva",
        "sale_date": "2020-11-07",
        "lot_number": "80",
        "brand": "Omega",
        "model": "Speedmaster Professional 'Pre-Moon'",
        "reference": "105.012-65",
        "description": "Omega Speedmaster Professional ref. 105.012-65, acciaio, Cal.321, quadrante 'Step Dial', 1965 - modello NASA certificato",
        "year_made": "1965",
        "condition": "Good",
        "estimate_low_chf": 18000,
        "estimate_high_chf": 30000,
        "hammer_price_chf": 40320,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 50800,
        "is_record": False,
        "notes": "Cal.321 'dot over 90' quadrante",
    },

    # Speedmaster CK2998 prima versione - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2018-11-12",
        "lot_number": "77",
        "brand": "Omega",
        "model": "Speedmaster",
        "reference": "CK2998",
        "description": "Omega Speedmaster ref. CK2998-4, acciaio, prima generazione Speedmaster 1957, cal.321 a 12 ore",
        "year_made": "1959",
        "condition": "Good",
        "estimate_low_chf": 25000,
        "estimate_high_chf": 50000,
        "hammer_price_chf": 63000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 79400,
        "is_record": False,
        "notes": "Esemplare originale con indicatore ore alla 12",
    },

    # Speedmaster 145.012 'Ed White' - Antiquorum
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2019-05-11",
        "lot_number": "219",
        "brand": "Omega",
        "model": "Speedmaster Professional 'Ed White'",
        "reference": "145.012",
        "description": "Omega Speedmaster Professional ref. 145.012-67, acciaio, Cal.321, quadrante 'Ed White' 1967",
        "year_made": "1967",
        "condition": "Excellent",
        "estimate_low_chf": 15000,
        "estimate_high_chf": 25000,
        "hammer_price_chf": 30240,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 38100,
        "is_record": False,
    },

    # Speedmaster 'Alaska Project' prototipo NASA - Christie's record
    {
        "auction_house": "Christie's",
        "sale_name": "Exceptional Watches",
        "sale_location": "Geneva",
        "sale_date": "2020-11-09",
        "lot_number": "188",
        "brand": "Omega",
        "model": "Speedmaster 'Alaska Project'",
        "reference": "ST 145.0022",
        "description": "Omega Speedmaster 'Alaska Project' prototipo NASA Phase I, acciaio, cassa rossa, 1969 - uno di soli 6 esemplari",
        "year_made": "1970",
        "condition": "Good",
        "estimate_low_chf": 180000,
        "estimate_high_chf": 360000,
        "hammer_price_chf": 3087900,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 3890700,
        "is_record": True,
        "notes": "Record mondiale per uno Speedmaster. Prototipo NASA unico con cassa rossa protettiva.",
    },

    # Speedmaster 3592.50 'Black Dial' - Bonhams
    {
        "auction_house": "Bonhams",
        "sale_name": "Watches",
        "sale_location": "London",
        "sale_date": "2021-04-20",
        "lot_number": "44",
        "brand": "Omega",
        "model": "Speedmaster Professional",
        "reference": "3590.50",
        "description": "Omega Speedmaster Professional ref. 3590.50, acciaio, fullset 1993",
        "year_made": "1993",
        "condition": "Excellent",
        "estimate_low_chf": 3000,
        "estimate_high_chf": 5000,
        "hammer_price_chf": 4725,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 5950,
        "is_record": False,
    },

    # =========================================================================
    # CARTIER CRASH
    # =========================================================================

    # Cartier Crash London 1967 originale - Christie's record
    {
        "auction_house": "Christie's",
        "sale_name": "Rare Watches",
        "sale_location": "London",
        "sale_date": "2020-11-24",
        "lot_number": "47",
        "brand": "Cartier",
        "model": "Crash",
        "reference": "2396",
        "description": "Cartier Crash London ref. 2396, oro giallo 18k, quadrante stretto distorto, circa 1967 - tra i primi esemplari prodotti",
        "year_made": "1967",
        "condition": "Good",
        "estimate_low_chf": 50000,
        "estimate_high_chf": 100000,
        "hammer_price_chf": 168000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 211700,
        "is_record": False,
        "notes": "Primissima produzione Crash, circa 1967-1970",
    },

    # Cartier Crash acciaio - Artcurial Paris 2021
    {
        "auction_house": "Artcurial",
        "sale_name": "Automobiles et Montres de Prestige",
        "sale_location": "Paris",
        "sale_date": "2021-12-14",
        "lot_number": "177",
        "brand": "Cartier",
        "model": "Crash",
        "reference": "1997",
        "description": "Cartier Crash acciaio, misura grande, Paris, nuovissimo, edizione 2016",
        "year_made": "2016",
        "condition": "Mint",
        "estimate_low_chf": 15000,
        "estimate_high_chf": 25000,
        "hammer_price_chf": 22050,
        "buyer_premium_pct": 28.0,
        "total_price_chf": 28200,
        "is_record": False,
    },

    # Cartier Crash Paris oro giallo originale - Sotheby's
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-11-14",
        "lot_number": "333",
        "brand": "Cartier",
        "model": "Crash",
        "reference": "2788",
        "description": "Cartier Crash Paris, oro giallo 18k, quadrante distorto, anni '90",
        "year_made": "1995",
        "condition": "Good",
        "estimate_low_chf": 20000,
        "estimate_high_chf": 35000,
        "hammer_price_chf": 29400,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 37000,
        "is_record": False,
    },

    # =========================================================================
    # CARTIER SANTOS-DUMONT vintage
    # =========================================================================

    # Santos 'Pasha' de Cartier prototype - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2017-11-13",
        "lot_number": "48",
        "brand": "Cartier",
        "model": "Santos-Dumont",
        "reference": "W2006951",
        "description": "Cartier Santos-Dumont, oro giallo 18k, cassa quadrata firmata, quadrante argentato, 1970s",
        "year_made": "1975",
        "condition": "Good",
        "estimate_low_chf": 10000,
        "estimate_high_chf": 18000,
        "hammer_price_chf": 15750,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 19850,
        "is_record": False,
    },

    # Santos Galbée XL acciaio - Artcurial
    {
        "auction_house": "Artcurial",
        "sale_name": "Montres de Prestige",
        "sale_location": "Paris",
        "sale_date": "2022-10-24",
        "lot_number": "44",
        "brand": "Cartier",
        "model": "Santos Galbée",
        "reference": "2823",
        "description": "Cartier Santos Galbée XL, acciaio, quadrante argentato, bracciale acciaio integrato, 2008",
        "year_made": "2008",
        "condition": "Excellent",
        "estimate_low_chf": 3000,
        "estimate_high_chf": 5000,
        "hammer_price_chf": 4410,
        "buyer_premium_pct": 28.0,
        "total_price_chf": 5645,
        "is_record": False,
    },

    # =========================================================================
    # Altri risultati importanti — mix di case e brand
    # =========================================================================

    # Patek Philippe 5970P cronografo perpetuo platino - Sotheby's
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-05-11",
        "lot_number": "297",
        "brand": "Patek Philippe",
        "model": "Perpetual Calendar Chronograph",
        "reference": "5970P",
        "description": "Patek Philippe ref. 5970P-001, platino, cronografo bicompax, calendario perpetuo, 2009",
        "year_made": "2009",
        "condition": "Excellent",
        "estimate_low_chf": 200000,
        "estimate_high_chf": 350000,
        "hammer_price_chf": 315000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 396900,
        "is_record": False,
    },

    # Patek Philippe 5004P split seconds - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2020-05-11",
        "lot_number": "58",
        "brand": "Patek Philippe",
        "model": "Split-Seconds Perpetual Calendar",
        "reference": "5004P",
        "description": "Patek Philippe ref. 5004P, platino, rattrapante, calendario perpetuo, fasi di luna, 2008",
        "year_made": "2008",
        "condition": "Excellent",
        "estimate_low_chf": 500000,
        "estimate_high_chf": 800000,
        "hammer_price_chf": 693000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 873200,
        "is_record": False,
    },

    # Patek Philippe Grand Complications 5208P - Phillips
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XVI",
        "sale_location": "Geneva",
        "sale_date": "2023-11-11",
        "lot_number": "9",
        "brand": "Patek Philippe",
        "model": "Grand Complications",
        "reference": "5208P",
        "description": "Patek Philippe ref. 5208P-001, platino, minute repeater, instant jumping calendar, chronograph",
        "year_made": "2015",
        "condition": "Excellent",
        "estimate_low_chf": 350000,
        "estimate_high_chf": 600000,
        "hammer_price_chf": 504000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 635000,
        "is_record": False,
    },

    # Rolex Daytona 6241 acciaio 'black dial' - Phillips 2021
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XIII",
        "sale_location": "Geneva",
        "sale_date": "2021-05-08",
        "lot_number": "14",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "6241",
        "description": "Rolex Cosmograph Daytona ref. 6241, acciaio, quadrante nero, indici a barrette, 1969",
        "year_made": "1969",
        "condition": "Good",
        "estimate_low_chf": 120000,
        "estimate_high_chf": 240000,
        "hammer_price_chf": 264600,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 333400,
        "is_record": False,
    },

    # AP Royal Oak 15202BC oro bianco - Christie's 2022
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-11-07",
        "lot_number": "55",
        "brand": "Audemars Piguet",
        "model": "Royal Oak 'Jumbo' Extra-Thin",
        "reference": "15202BC",
        "description": "Audemars Piguet Royal Oak Jumbo ref. 15202BC.OO.0944BC.01, oro bianco 18k, quadrante argentato 'Tapisserie', 2016",
        "year_made": "2016",
        "condition": "Excellent",
        "estimate_low_chf": 70000,
        "estimate_high_chf": 110000,
        "hammer_price_chf": 102900,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 129700,
        "is_record": False,
    },

    # Richard Mille RM 052 Tourbillon 'Skull' - Phillips
    {
        "auction_house": "Phillips",
        "sale_name": "Hong Kong Watch Auction XII",
        "sale_location": "Hong Kong",
        "sale_date": "2021-07-11",
        "lot_number": "902",
        "brand": "Richard Mille",
        "model": "RM 052 Tourbillon",
        "reference": "RM 052",
        "description": "Richard Mille RM 052 Tourbillon 'Skull', titanio e oro rosé, n° 9/30",
        "year_made": "2012",
        "condition": "Excellent",
        "estimate_low_chf": 600000,
        "estimate_high_chf": 1000000,
        "hammer_price_chf": 956000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 1204500,
        "is_record": False,
    },

    # Vacheron Constantin 222 acciaio - Sotheby's 2022
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-11-14",
        "lot_number": "47",
        "brand": "Vacheron Constantin",
        "model": "222",
        "reference": "44018",
        "description": "Vacheron Constantin 222, acciaio, quadrante salmone, bracciale integrato, 1978 - rarissimo",
        "year_made": "1978",
        "condition": "Excellent",
        "estimate_low_chf": 40000,
        "estimate_high_chf": 80000,
        "hammer_price_chf": 113400,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 142900,
        "is_record": False,
        "notes": "Risposta di VC alla Royal Oak, rarissimo in acciaio",
    },

    # Jaeger-LeCoultre Reverso Grande Taille - Antiquorum
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2021-11-06",
        "lot_number": "159",
        "brand": "Jaeger-LeCoultre",
        "model": "Reverso Grande Taille",
        "reference": "270.8.62",
        "description": "Jaeger-LeCoultre Reverso Grande Taille ref. 270.8.62, acciaio, cassa reversibile, retro nero, anni '30 design",
        "year_made": "2001",
        "condition": "Excellent",
        "estimate_low_chf": 5000,
        "estimate_high_chf": 9000,
        "hammer_price_chf": 7560,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 9530,
        "is_record": False,
    },

    # Rolex Day-Date 1803 oro presidenziale - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2019-11-11",
        "lot_number": "74",
        "brand": "Rolex",
        "model": "Day-Date",
        "reference": "1803",
        "description": "Rolex Day-Date ref. 1803, oro giallo 18k, quadrante 'Stella' (lacca blu), bracciale presidenziale, 1972",
        "year_made": "1972",
        "condition": "Excellent",
        "estimate_low_chf": 15000,
        "estimate_high_chf": 25000,
        "hammer_price_chf": 27300,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 34400,
        "is_record": False,
    },

    # Patek Philippe Ellipse 3548 - Bonhams
    {
        "auction_house": "Bonhams",
        "sale_name": "Watches",
        "sale_location": "London",
        "sale_date": "2022-04-05",
        "lot_number": "53",
        "brand": "Patek Philippe",
        "model": "Golden Ellipse",
        "reference": "3548",
        "description": "Patek Philippe Golden Ellipse ref. 3548, oro giallo 18k, quadrante blu 'Cloisonné', 1971",
        "year_made": "1971",
        "condition": "Excellent",
        "estimate_low_chf": 20000,
        "estimate_high_chf": 35000,
        "hammer_price_chf": 31500,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 39700,
        "is_record": False,
    },

    # Rolex Milgauss 6541 prima versione - Phillips
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction VIII",
        "sale_location": "Geneva",
        "sale_date": "2018-11-10",
        "lot_number": "71",
        "brand": "Rolex",
        "model": "Milgauss",
        "reference": "6541",
        "description": "Rolex Milgauss ref. 6541, acciaio, prima versione con ghiera alluminio, quadrante nero, 1956",
        "year_made": "1956",
        "condition": "Good",
        "estimate_low_chf": 60000,
        "estimate_high_chf": 120000,
        "hammer_price_chf": 113400,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 142900,
        "is_record": False,
    },

    # AP Royal Oak Offshore Tourbillon Chronograph - Phillips HK
    {
        "auction_house": "Phillips",
        "sale_name": "Hong Kong Watch Auction X",
        "sale_location": "Hong Kong",
        "sale_date": "2019-11-27",
        "lot_number": "1001",
        "brand": "Audemars Piguet",
        "model": "Royal Oak Offshore Tourbillon Chronograph",
        "reference": "26388PO",
        "description": "Audemars Piguet Royal Oak Offshore Tourbillon Chronograph ref. 26388PO, oro rosé, scheletrato, n° 3/30",
        "year_made": "2017",
        "condition": "Mint",
        "estimate_low_chf": 250000,
        "estimate_high_chf": 400000,
        "hammer_price_chf": 365400,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 460400,
        "is_record": False,
    },

    # FP Journe Octa Automatique oro - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-11-07",
        "lot_number": "34",
        "brand": "F.P. Journe",
        "model": "Octa Automatique",
        "reference": "OCTA",
        "description": "F.P. Journe Octa Automatique, oro rosé 18k, quadrante oro, remontoir 80 sec, 2004",
        "year_made": "2004",
        "condition": "Excellent",
        "estimate_low_chf": 25000,
        "estimate_high_chf": 45000,
        "hammer_price_chf": 44100,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 55600,
        "is_record": False,
    },

    # Rolex Explorer II 1655 'Steve McQueen' - Sotheby's
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-05-11",
        "lot_number": "174",
        "brand": "Rolex",
        "model": "Explorer II 'Steve McQueen'",
        "reference": "1655",
        "description": "Rolex Explorer II ref. 1655 'Steve McQueen', acciaio, lancetta arancione, quadrante bianco, 1975",
        "year_made": "1975",
        "condition": "Good",
        "estimate_low_chf": 20000,
        "estimate_high_chf": 40000,
        "hammer_price_chf": 50400,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 63500,
        "is_record": False,
    },

    # Patek Philippe Ref. 5078 Minute Repeater - Phillips
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XV",
        "sale_location": "Geneva",
        "sale_date": "2022-11-05",
        "lot_number": "28",
        "brand": "Patek Philippe",
        "model": "Minute Repeater",
        "reference": "5078G",
        "description": "Patek Philippe Minute Repeater ref. 5078G-001, oro bianco 18k, quadrante cloisonné 'Paysage', 2014",
        "year_made": "2014",
        "condition": "Excellent",
        "estimate_low_chf": 100000,
        "estimate_high_chf": 180000,
        "hammer_price_chf": 176400,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 222300,
        "is_record": False,
    },

    # Rolex Daytona 6264 acciaio - Antiquorum 2019
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2019-11-09",
        "lot_number": "267",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "6264",
        "description": "Rolex Cosmograph Daytona ref. 6264, acciaio, quadrante nero, ghiera tachimetrica, 1970",
        "year_made": "1970",
        "condition": "Good",
        "estimate_low_chf": 80000,
        "estimate_high_chf": 150000,
        "hammer_price_chf": 145600,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 183500,
        "is_record": False,
    },

    # Richard Mille RM 056 Tourbillon Sapphire - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2013-11-11",
        "lot_number": "145",
        "brand": "Richard Mille",
        "model": "RM 056 Tourbillon",
        "reference": "RM 056",
        "description": "Richard Mille RM 056 Tourbillon Sapphire, cassa in cristallo di zaffiro, n° 3/5",
        "year_made": "2012",
        "condition": "Excellent",
        "estimate_low_chf": 500000,
        "estimate_high_chf": 800000,
        "hammer_price_chf": 1400000,
        "buyer_premium_pct": 12.0,
        "total_price_chf": 1568000,
        "is_record": True,
        "notes": "Record per Richard Mille al momento dell'asta",
    },

    # Omega Seamaster 300 'Broad Arrow' 2913 - Sotheby's
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2021-11-13",
        "lot_number": "55",
        "brand": "Omega",
        "model": "Seamaster 300",
        "reference": "2913",
        "description": "Omega Seamaster 300 ref. 2913-3 'Broad Arrow', acciaio, quadrante nero glossy, 1957",
        "year_made": "1957",
        "condition": "Good",
        "estimate_low_chf": 8000,
        "estimate_high_chf": 14000,
        "hammer_price_chf": 17640,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 22200,
        "is_record": False,
    },

    # Patek Philippe 5980/1AR Nautilus Cronografo - Phillips
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XI",
        "sale_location": "Geneva",
        "sale_date": "2020-05-09",
        "lot_number": "39",
        "brand": "Patek Philippe",
        "model": "Nautilus Chronograph",
        "reference": "5980/1AR",
        "description": "Patek Philippe Nautilus Chronograph ref. 5980/1AR-001, oro rosé e acciaio, flyback, 2007",
        "year_made": "2007",
        "condition": "Excellent",
        "estimate_low_chf": 80000,
        "estimate_high_chf": 130000,
        "hammer_price_chf": 107100,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 134900,
        "is_record": False,
    },

    # Breguet Tourbillon No. 4 - Sotheby's record storico
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "1999-05-16",
        "lot_number": "11",
        "brand": "Breguet",
        "model": "Tourbillon",
        "reference": "No. 4",
        "description": "Breguet Tourbillon No. 4, oro giallo, pezzo storico dell'orologeria, circa 1800",
        "year_made": "1800",
        "condition": "Good",
        "estimate_low_chf": 1500000,
        "estimate_high_chf": 2500000,
        "hammer_price_chf": 2474400,
        "buyer_premium_pct": 15.0,
        "total_price_chf": 2845560,
        "is_record": True,
        "notes": "Tourbillon originale Breguet, pezzo di inestimabile valore storico",
    },

    # Rolex Daytona 116520 'Series I' - Artcurial
    {
        "auction_house": "Artcurial",
        "sale_name": "Automobiles et Montres",
        "sale_location": "Paris",
        "sale_date": "2021-02-22",
        "lot_number": "88",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "116520",
        "description": "Rolex Cosmograph Daytona ref. 116520, acciaio, quadrante bianco 'panda', cal. 4130, 2000 - prima serie",
        "year_made": "2000",
        "condition": "Excellent",
        "estimate_low_chf": 12000,
        "estimate_high_chf": 20000,
        "hammer_price_chf": 18900,
        "buyer_premium_pct": 28.0,
        "total_price_chf": 24200,
        "is_record": False,
    },

    # Vacheron Const. Tour de l'Ile - Christie's 2005
    {
        "auction_house": "Christie's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2005-11-14",
        "lot_number": "212",
        "brand": "Vacheron Constantin",
        "model": "Tour de l'Ile",
        "reference": "57260",
        "description": "Vacheron Constantin Tour de l'Ile, edizione speciale 250° anniversario, oro giallo 18k, 16 complicazioni",
        "year_made": "2005",
        "condition": "Mint",
        "estimate_low_chf": 1200000,
        "estimate_high_chf": 1800000,
        "hammer_price_chf": 1550000,
        "buyer_premium_pct": 15.0,
        "total_price_chf": 1782500,
        "is_record": False,
        "notes": "L'orologio con più complicazioni del mondo al momento della produzione",
    },

    # Omega Constellation 'Pie Pan' - Antiquorum 2020
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2020-11-07",
        "lot_number": "133",
        "brand": "Omega",
        "model": "Constellation",
        "reference": "2852",
        "description": "Omega Constellation 'Pie Pan', acciaio, quadrante stellato, anno 1959",
        "year_made": "1959",
        "condition": "Good",
        "estimate_low_chf": 2500,
        "estimate_high_chf": 4500,
        "hammer_price_chf": 4536,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 5715,
        "is_record": False,
    },

    # Rolex Submariner 16800 'Maxi Dial' - Christie's
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2021-05-10",
        "lot_number": "28",
        "brand": "Rolex",
        "model": "Submariner Date",
        "reference": "16800",
        "description": "Rolex Submariner Date ref. 16800 'Maxi Dial', acciaio, ghiera alluminio nera, quadrante Maxi, 1979",
        "year_made": "1979",
        "condition": "Excellent",
        "estimate_low_chf": 12000,
        "estimate_high_chf": 20000,
        "hammer_price_chf": 22680,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 28600,
        "is_record": False,
    },

    # =========================================================================
    # Risultati più recenti 2024
    # =========================================================================

    # Patek Philippe 5726A Annual Calendar - Phillips Geneva XVII
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XVII",
        "sale_location": "Geneva",
        "sale_date": "2024-05-11",
        "lot_number": "41",
        "brand": "Patek Philippe",
        "model": "Annual Calendar",
        "reference": "5726A",
        "description": "Patek Philippe Annual Calendar Moonphase ref. 5726A-001, acciaio, quadrante blu, 2017",
        "year_made": "2017",
        "condition": "Excellent",
        "estimate_low_chf": 45000,
        "estimate_high_chf": 75000,
        "hammer_price_chf": 60000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 75600,
        "is_record": False,
    },

    # Rolex Submariner 126610LN 2021 - Bonhams
    {
        "auction_house": "Bonhams",
        "sale_name": "Watches",
        "sale_location": "London",
        "sale_date": "2024-03-19",
        "lot_number": "88",
        "brand": "Rolex",
        "model": "Submariner Date",
        "reference": "126610LN",
        "description": "Rolex Submariner Date ref. 126610LN, acciaio, ghiera Cerachrom nera, fullset 2021",
        "year_made": "2021",
        "condition": "Mint",
        "estimate_low_chf": 10000,
        "estimate_high_chf": 15000,
        "hammer_price_chf": 11550,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 14550,
        "is_record": False,
    },

    # AP Royal Oak 15500ST 41mm - Sotheby's 2024
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2024-05-12",
        "lot_number": "198",
        "brand": "Audemars Piguet",
        "model": "Royal Oak",
        "reference": "15500ST",
        "description": "Audemars Piguet Royal Oak ref. 15500ST.OO.1220ST.01, acciaio, quadrante blu 'Tapisserie', 41mm, 2023",
        "year_made": "2023",
        "condition": "Mint",
        "estimate_low_chf": 22000,
        "estimate_high_chf": 35000,
        "hammer_price_chf": 25200,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 31750,
        "is_record": False,
    },

    # Rolex Daytona 116506 Platino - Phillips 2024
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XVII",
        "sale_location": "Geneva",
        "sale_date": "2024-05-11",
        "lot_number": "23",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "116506",
        "description": "Rolex Cosmograph Daytona ref. 116506, platino, ghiera 'Ice Blue', quadrante 'Ice Blue', fullset 2019",
        "year_made": "2019",
        "condition": "Mint",
        "estimate_low_chf": 60000,
        "estimate_high_chf": 90000,
        "hammer_price_chf": 72000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 90700,
        "is_record": False,
    },

    # FP Journe Chronomètre Bleu acciaio - Phillips 2023
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XVI",
        "sale_location": "Geneva",
        "sale_date": "2023-11-11",
        "lot_number": "11",
        "brand": "F.P. Journe",
        "model": "Chronomètre Bleu",
        "reference": "CB",
        "description": "F.P. Journe Chronomètre Bleu, acciaio, quadrante blu tantalio, esemplare 40mm, 2012",
        "year_made": "2012",
        "condition": "Excellent",
        "estimate_low_chf": 80000,
        "estimate_high_chf": 140000,
        "hammer_price_chf": 126000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 158800,
        "is_record": False,
    },

    # Richard Mille RM 67-02 Sprinter - Christie's 2023
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2023-11-13",
        "lot_number": "78",
        "brand": "Richard Mille",
        "model": "RM 67-02",
        "reference": "RM 67-02",
        "description": "Richard Mille RM 67-02 'Sprint' Wayde van Niekerk, NTPT carbon, acciaio, n° 12/50",
        "year_made": "2018",
        "condition": "Excellent",
        "estimate_low_chf": 120000,
        "estimate_high_chf": 200000,
        "hammer_price_chf": 139000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 175100,
        "is_record": False,
    },

    # Omega Speedmaster Moonwatch 145.022 - Artcurial 2022
    {
        "auction_house": "Artcurial",
        "sale_name": "Montres de Prestige",
        "sale_location": "Paris",
        "sale_date": "2022-06-13",
        "lot_number": "31",
        "brand": "Omega",
        "model": "Speedmaster Professional Moonwatch",
        "reference": "145.022",
        "description": "Omega Speedmaster Professional Moonwatch ref. 145.022-69 ST, cal. 861, 1969",
        "year_made": "1969",
        "condition": "Good",
        "estimate_low_chf": 6000,
        "estimate_high_chf": 10000,
        "hammer_price_chf": 8820,
        "buyer_premium_pct": 28.0,
        "total_price_chf": 11300,
        "is_record": False,
    },

    # Patek Philippe 5711/1A acciaio blue - Antiquorum 2022
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-11-05",
        "lot_number": "258",
        "brand": "Patek Philippe",
        "model": "Nautilus",
        "reference": "5711/1A",
        "description": "Patek Philippe Nautilus ref. 5711/1A-010, acciaio, quadrante blu 'sunburst', fullset 2016",
        "year_made": "2016",
        "condition": "Excellent",
        "estimate_low_chf": 55000,
        "estimate_high_chf": 90000,
        "hammer_price_chf": 84000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 105800,
        "is_record": False,
    },

    # Rolex Submariner 6536 "Small Crown" - Phillips 2022
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XV",
        "sale_location": "Geneva",
        "sale_date": "2022-11-05",
        "lot_number": "78",
        "brand": "Rolex",
        "model": "Submariner",
        "reference": "6536",
        "description": "Rolex Submariner ref. 6536/1, acciaio, 'Small Crown', quadrante Explorer, 1956",
        "year_made": "1956",
        "condition": "Good",
        "estimate_low_chf": 60000,
        "estimate_high_chf": 100000,
        "hammer_price_chf": 88200,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 111100,
        "is_record": False,
    },

    # AP Royal Oak 15400ST 41mm - Christie's 2023
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2023-05-13",
        "lot_number": "54",
        "brand": "Audemars Piguet",
        "model": "Royal Oak",
        "reference": "15400ST",
        "description": "Audemars Piguet Royal Oak ref. 15400ST.OO.1220ST.01, acciaio, 41mm, quadrante bianco, 2018",
        "year_made": "2018",
        "condition": "Excellent",
        "estimate_low_chf": 20000,
        "estimate_high_chf": 32000,
        "hammer_price_chf": 22680,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 28600,
        "is_record": False,
    },

    # Cartier Santos-Dumont Extra-Flat oro - Artcurial 2023
    {
        "auction_house": "Artcurial",
        "sale_name": "Montres de Prestige",
        "sale_location": "Paris",
        "sale_date": "2023-09-24",
        "lot_number": "21",
        "brand": "Cartier",
        "model": "Santos-Dumont",
        "reference": "W2006951",
        "description": "Cartier Santos-Dumont Extra-Flat, oro giallo 18k, quadrante argentato, 2010",
        "year_made": "2010",
        "condition": "Excellent",
        "estimate_low_chf": 8000,
        "estimate_high_chf": 14000,
        "hammer_price_chf": 11025,
        "buyer_premium_pct": 28.0,
        "total_price_chf": 14100,
        "is_record": False,
    },

    # FP Journe Centigraphe Souverain acciaio - Phillips 2022
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XIV",
        "sale_location": "Geneva",
        "sale_date": "2022-05-07",
        "lot_number": "23",
        "brand": "F.P. Journe",
        "model": "Centigraphe Souverain",
        "reference": "CSG",
        "description": "F.P. Journe Centigraphe Souverain, acciaio, cronografo al centesimo di secondo, 2009",
        "year_made": "2009",
        "condition": "Excellent",
        "estimate_low_chf": 50000,
        "estimate_high_chf": 80000,
        "hammer_price_chf": 88200,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 111100,
        "is_record": False,
    },

    # Rolex Submariner 116613LB oro e acciaio 'Bluesy' - Bonhams 2022
    {
        "auction_house": "Bonhams",
        "sale_name": "Watches & Wristwatches",
        "sale_location": "London",
        "sale_date": "2022-09-20",
        "lot_number": "55",
        "brand": "Rolex",
        "model": "Submariner Date 'Bluesy'",
        "reference": "116613LB",
        "description": "Rolex Submariner Date ref. 116613LB 'Bluesy', acciaio e oro giallo, ghiera ceramica blu, 2015",
        "year_made": "2015",
        "condition": "Excellent",
        "estimate_low_chf": 8000,
        "estimate_high_chf": 12000,
        "hammer_price_chf": 10080,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 12700,
        "is_record": False,
    },

    # Patek Philippe 5726A Annual Calendar Moonphase - Antiquorum 2023
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2023-11-04",
        "lot_number": "124",
        "brand": "Patek Philippe",
        "model": "Annual Calendar",
        "reference": "5726A",
        "description": "Patek Philippe Annual Calendar ref. 5726A-001, acciaio, fasi di luna, 2021",
        "year_made": "2021",
        "condition": "Mint",
        "estimate_low_chf": 50000,
        "estimate_high_chf": 80000,
        "hammer_price_chf": 63000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 79400,
        "is_record": False,
    },

    # Omega Speedmaster 'Snoopy' Silver Snoopy Award - Phillips 2021
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XIII",
        "sale_location": "Geneva",
        "sale_date": "2021-05-08",
        "lot_number": "93",
        "brand": "Omega",
        "model": "Speedmaster Professional 'Snoopy'",
        "reference": "3578.51",
        "description": "Omega Speedmaster Professional 'Silver Snoopy Award' ref. 3578.51.00, acciaio, 2003",
        "year_made": "2003",
        "condition": "Mint",
        "estimate_low_chf": 5000,
        "estimate_high_chf": 9000,
        "hammer_price_chf": 11340,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 14300,
        "is_record": False,
    },

    # Rolex Daytona 6265 oro bianco - Antiquorum 2018
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2018-11-10",
        "lot_number": "178",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "6265",
        "description": "Rolex Cosmograph Daytona ref. 6265, oro bianco 18k, quadrante nero con contatori bianchi, 1978",
        "year_made": "1978",
        "condition": "Excellent",
        "estimate_low_chf": 150000,
        "estimate_high_chf": 250000,
        "hammer_price_chf": 302400,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 381000,
        "is_record": False,
    },

    # AP Royal Oak Offshore 'Diver' 15703 titanio - Sotheby's 2021
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2021-11-13",
        "lot_number": "88",
        "brand": "Audemars Piguet",
        "model": "Royal Oak Offshore Diver",
        "reference": "15703ST",
        "description": "Audemars Piguet Royal Oak Offshore Diver ref. 15703ST.OO.A002CA.01, acciaio, 2015",
        "year_made": "2015",
        "condition": "Excellent",
        "estimate_low_chf": 10000,
        "estimate_high_chf": 18000,
        "hammer_price_chf": 14700,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 18500,
        "is_record": False,
    },

    # Cartier Tank Louis Cartier 1970s - Christie's 2021
    {
        "auction_house": "Christie's",
        "sale_name": "Watches Online",
        "sale_location": "Geneva",
        "sale_date": "2021-05-19",
        "lot_number": "19",
        "brand": "Cartier",
        "model": "Tank Louis Cartier",
        "reference": "2441",
        "description": "Cartier Tank Louis Cartier, oro giallo 18k, quadrante bianco romano, 1970s",
        "year_made": "1975",
        "condition": "Good",
        "estimate_low_chf": 5000,
        "estimate_high_chf": 9000,
        "hammer_price_chf": 7560,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 9530,
        "is_record": False,
    },

    # FP Journe Tourbillon à Résonance - Phillips 2024
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XVII",
        "sale_location": "Geneva",
        "sale_date": "2024-05-11",
        "lot_number": "4",
        "brand": "F.P. Journe",
        "model": "Tourbillon à Résonance",
        "reference": "TRES",
        "description": "F.P. Journe Tourbillon à Résonance, oro rosé 18k, doppio tourbillon in risonanza, edizione limitata 10 esemplari",
        "year_made": "2021",
        "condition": "Mint",
        "estimate_low_chf": 600000,
        "estimate_high_chf": 1000000,
        "hammer_price_chf": 882000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 1111300,
        "is_record": False,
    },

    # Richard Mille RM 27-04 Tourbillon 'Nadal' - Phillips HK 2022
    {
        "auction_house": "Phillips",
        "sale_name": "Hong Kong Watch Auction XIV",
        "sale_location": "Hong Kong",
        "sale_date": "2022-07-11",
        "lot_number": "1106",
        "brand": "Richard Mille",
        "model": "RM 27-04 Tourbillon",
        "reference": "RM 27-04",
        "description": "Richard Mille RM 27-04 Tourbillon Rafael Nadal, NTPT carbon, n° 5/50",
        "year_made": "2021",
        "condition": "Mint",
        "estimate_low_chf": 600000,
        "estimate_high_chf": 900000,
        "hammer_price_chf": 780000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 982800,
        "is_record": False,
    },

    # Rolex 'Ovettone' 6098 Datejust vintage - Phillips 2020
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XI",
        "sale_location": "Geneva",
        "sale_date": "2020-05-09",
        "lot_number": "51",
        "brand": "Rolex",
        "model": "Datejust 'Ovettone'",
        "reference": "6098",
        "description": "Rolex Datejust ref. 6098 'Ovettone', acciaio, cassa ovale, calibro 640, quadrante argentato, 1950",
        "year_made": "1950",
        "condition": "Good",
        "estimate_low_chf": 15000,
        "estimate_high_chf": 30000,
        "hammer_price_chf": 34020,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 42900,
        "is_record": False,
    },

    # Patek Philippe 5960 Annual Calendar Chronograph - Antiquorum 2021
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2021-05-08",
        "lot_number": "234",
        "brand": "Patek Philippe",
        "model": "Annual Calendar Chronograph",
        "reference": "5960P",
        "description": "Patek Philippe Annual Calendar Chronograph ref. 5960P-015, platino, flyback, 2011",
        "year_made": "2011",
        "condition": "Excellent",
        "estimate_low_chf": 100000,
        "estimate_high_chf": 170000,
        "hammer_price_chf": 138600,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 174600,
        "is_record": False,
    },

    # Omega Seamaster Diver 300M 'James Bond' - Artcurial 2021
    {
        "auction_house": "Artcurial",
        "sale_name": "Montres de Prestige",
        "sale_location": "Paris",
        "sale_date": "2021-12-14",
        "lot_number": "222",
        "brand": "Omega",
        "model": "Seamaster Diver 300M",
        "reference": "2541.80",
        "description": "Omega Seamaster Diver 300M ref. 2541.80.00 'James Bond', acciaio, ghiera alluminio blu, 1995",
        "year_made": "1995",
        "condition": "Excellent",
        "estimate_low_chf": 3000,
        "estimate_high_chf": 5500,
        "hammer_price_chf": 5040,
        "buyer_premium_pct": 28.0,
        "total_price_chf": 6450,
        "is_record": False,
    },

    # Rolex GMT Master II 126710BLNR 'Batman' - Christie's 2022
    {
        "auction_house": "Christie's",
        "sale_name": "Watches Online",
        "sale_location": "Geneva",
        "sale_date": "2022-05-18",
        "lot_number": "144",
        "brand": "Rolex",
        "model": "GMT-Master II 'Batman'",
        "reference": "126710BLNR",
        "description": "Rolex GMT-Master II ref. 126710BLNR 'Batman', acciaio, ghiera Cerachrom blu-nera, oystersteel jubilee, 2019",
        "year_made": "2019",
        "condition": "Mint",
        "estimate_low_chf": 12000,
        "estimate_high_chf": 18000,
        "hammer_price_chf": 14700,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 18500,
        "is_record": False,
    },

    # Vacheron Constantin Patrimony Traditionelle 'Ultra-Thin' platino - Sotheby's 2022
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-11-14",
        "lot_number": "211",
        "brand": "Vacheron Constantin",
        "model": "Patrimony Traditionnelle Ultra-Thin",
        "reference": "81180",
        "description": "Vacheron Constantin Patrimony Traditionnelle Ultra-Thin ref. 81180/000P, platino, quadrante bianco, 2018",
        "year_made": "2018",
        "condition": "Excellent",
        "estimate_low_chf": 20000,
        "estimate_high_chf": 35000,
        "hammer_price_chf": 27300,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 34400,
        "is_record": False,
    },

    # Rolex Daytona 116523 'Sundust' oro rosé e acciaio - Bonhams 2023
    {
        "auction_house": "Bonhams",
        "sale_name": "Watches",
        "sale_location": "London",
        "sale_date": "2023-09-19",
        "lot_number": "66",
        "brand": "Rolex",
        "model": "Daytona",
        "reference": "116523",
        "description": "Rolex Cosmograph Daytona ref. 116523, acciaio e oro Everose, quadrante 'Sundust' meteorite, 2014",
        "year_made": "2014",
        "condition": "Excellent",
        "estimate_low_chf": 18000,
        "estimate_high_chf": 26000,
        "hammer_price_chf": 22050,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 27800,
        "is_record": False,
    },

    # Patek Philippe 5980R Nautilus Chronograph oro rosé - Christie's 2023
    {
        "auction_house": "Christie's",
        "sale_name": "Watches",
        "sale_location": "Geneva",
        "sale_date": "2023-11-13",
        "lot_number": "198",
        "brand": "Patek Philippe",
        "model": "Nautilus Chronograph",
        "reference": "5980R",
        "description": "Patek Philippe Nautilus Chronograph ref. 5980R-001, oro rosé 18k, quadrante cioccolato, flyback, 2015",
        "year_made": "2015",
        "condition": "Excellent",
        "estimate_low_chf": 100000,
        "estimate_high_chf": 160000,
        "hammer_price_chf": 126000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 158800,
        "is_record": False,
    },

    # A. Lange & Söhne Datograph UP/DOWN - Phillips 2021
    {
        "auction_house": "Phillips",
        "sale_name": "Geneva Watch Auction XIII",
        "sale_location": "Geneva",
        "sale_date": "2021-05-08",
        "lot_number": "48",
        "brand": "A. Lange & Söhne",
        "model": "Datograph Up/Down",
        "reference": "405.035",
        "description": "A. Lange & Söhne Datograph Up/Down ref. 405.035, platino, quadrante argenté, 2013",
        "year_made": "2013",
        "condition": "Excellent",
        "estimate_low_chf": 60000,
        "estimate_high_chf": 100000,
        "hammer_price_chf": 82000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 103300,
        "is_record": False,
        "notes": "Calibro L951.6 con indicatore riserva di carica",
    },

    # IWC Big Pilot Top Gun - Antiquorum 2022
    {
        "auction_house": "Antiquorum",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-05-08",
        "lot_number": "312",
        "brand": "IWC",
        "model": "Big Pilot's Watch Top Gun",
        "reference": "IW506901",
        "description": "IWC Big Pilot's Watch Top Gun ref. IW506901, ceramica nera, edizione speciale Navy TOPGUN, 2019",
        "year_made": "2019",
        "condition": "Mint",
        "estimate_low_chf": 8000,
        "estimate_high_chf": 13000,
        "hammer_price_chf": 10080,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 12700,
        "is_record": False,
    },

    # Patek Philippe 5235/50G Annual Calendar Regulator - Sotheby's 2022
    {
        "auction_house": "Sotheby's",
        "sale_name": "Important Watches",
        "sale_location": "Geneva",
        "sale_date": "2022-05-11",
        "lot_number": "322",
        "brand": "Patek Philippe",
        "model": "Annual Calendar Regulator",
        "reference": "5235/50G",
        "description": "Patek Philippe Annual Calendar Regulator ref. 5235/50G-001, oro bianco 18k, display a regolatore, 2018",
        "year_made": "2018",
        "condition": "Excellent",
        "estimate_low_chf": 50000,
        "estimate_high_chf": 80000,
        "hammer_price_chf": 63000,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 79400,
        "is_record": False,
    },

    # Audemars Piguet Royal Oak Concept 26223 - Phillips HK 2022
    {
        "auction_house": "Phillips",
        "sale_name": "Hong Kong Watch Auction XIV",
        "sale_location": "Hong Kong",
        "sale_date": "2022-07-11",
        "lot_number": "1008",
        "brand": "Audemars Piguet",
        "model": "Royal Oak Concept Flying Tourbillon GMT",
        "reference": "26589IO",
        "description": "Audemars Piguet Royal Oak Concept Flying Tourbillon GMT ref. 26589IO, titanio, rubber, 2021",
        "year_made": "2021",
        "condition": "Mint",
        "estimate_low_chf": 100000,
        "estimate_high_chf": 160000,
        "hammer_price_chf": 138600,
        "buyer_premium_pct": 26.0,
        "total_price_chf": 174600,
        "is_record": False,
    },

    # Omega Flightmaster 910 - Artcurial 2020
    {
        "auction_house": "Artcurial",
        "sale_name": "Montres de Prestige",
        "sale_location": "Paris",
        "sale_date": "2020-10-26",
        "lot_number": "55",
        "brand": "Omega",
        "model": "Flightmaster",
        "reference": "910",
        "description": "Omega Flightmaster ref. 910.005, acciaio, quadrante nero, cronografo, 1969 - rarissimo",
        "year_made": "1969",
        "condition": "Good",
        "estimate_low_chf": 6000,
        "estimate_high_chf": 10000,
        "hammer_price_chf": 12600,
        "buyer_premium_pct": 28.0,
        "total_price_chf": 16100,
        "is_record": False,
        "notes": "Raro cronografo piloti con navigazione",
    },

]


def get_seed_data() -> list[dict]:
    """Ritorna tutti i dati storici."""
    return AUCTION_RESULTS
