import { createContext, useContext, useState, ReactNode } from 'react'

export type Lang = 'en' | 'it'

const T = {
  en: {
    // Sidebar
    dashboard: 'Dashboard',
    marketFeed: 'Watch Search',
    portfolio: 'Encyclopedia',
    priceAlerts: 'Price Alerts',
    analytics: 'Analytics',
    upgradePro: 'Upgrade to Pro',
    support: 'Support',
    settings: 'Settings',

    // TopBar
    searchPlaceholder: 'Search reference...',
    marketIndexes: 'Market Indexes',
    auctions: 'Auctions',
    valuation: 'Valuation',

    // HomePage
    watchWorldTitle: 'Luxury Watch Market',
    watchWorldSub: 'Global overview — curated market intelligence for serious collectors',
    marketHighlightsTitle: 'Market Highlights',
    auctionCalendarTitle: 'Upcoming Auctions',
    auctionResultsTitle: 'Latest Auction Results',
    auctionResultsSub: 'Highest hammer prices from recent major sales',
    topInvestmentTitle: 'Top Investment Pick',
    topInvestmentSub: '12-month market analysis',
    recentSearchesTitle: 'Recent Searches',
    recentSearchesSub: 'Track price evolution on your watched references',
    viewAll: 'View all',
    searchNow: 'Search now',
    invest_score: 'Investment Score',
    invest_12m: '12-month return',
    invest_volume: 'Market volume',
    invest_liquidity: 'Liquidity',
    auction_house: 'Auction House',
    auction_date: 'Date',
    auction_location: 'Location',
    auction_lots: 'Key Lots',
    auction_hammer: 'Hammer Price',
    auction_estimate: 'Estimate',
    auction_result: 'Result',
    noRecentSearches: 'No recent searches yet',
    noRecentSub: 'Start a scan to build your history',
    priceUp: 'above estimate',
    priceAbove: 'vs estimate',
    loading: 'Loading…',

    // SearchPage
    scanTerminal: 'Scan Terminal',
    marketIntelligence: 'Market Intelligence',
    referenceLabel: 'Watch Reference',
    referencePlaceholder: 'e.g. 116610LN · 5711/1A · 126710BLNR',
    maxPriceLabel: 'Max Price (€) — optional',
    maxPricePlaceholder: 'e.g. 12000',
    scanButton: 'Scan',
    scanningButton: 'Scanning…',
    quickSearch: 'Quick:',
    scanFromPhoto: 'Scan from photo',
    identifying: 'Identifying…',
    scanningFor: 'Scanning for',
    agentsActive: 'Parallel agents active',
    scanDuration: 'Scan takes 40–60 seconds',
    scanDone: 'Done',
    resultsFound: 'RESULTS FOUND',
    liveMarketFeed: 'LIVE MARKET FEED',
    sortPrice: 'Sort: Price Low to High',
    priceRange: 'Price Range (€)',
    accessories: 'Accessories',
    location: 'Location',
    marketSource: 'Market Source',
    worldwide: 'Worldwide',
    italy: 'Italy',
    europe: 'Europe',
    allAccessories: 'All',
    boxPapers: 'Box & Papers',
    watchOnly: 'Watch Only',
    filterSeller: 'Filter seller…',
    viewDetails: 'View Details',
    contactSeller: 'Contact Seller',
    noResults: 'No results with current filters',
    noResultsSub: 'Try changing location or accessory filter',
    noListings: 'No listings for',
    noListingsSub: 'Try without max price or use a different reference',
    bestPrice: 'Best Price',
    topRanked: 'TOP RANKED LISTING',
    bestDeal: 'Best Deal',
    marketPrice: 'Market Price',
    socialVerified: 'Social Verified',
    completedIn: 'Completed in',

    // VerificationPage
    coevTitle: 'Coevality Verification Engine',
    coevSub: 'Strict adherence to archival coevality rules. Validating case, caliber, and cosmetic coherence.',
    saveAnalysis: 'Save Analysis',
    exportPdf: 'Export PDF Report',
    step01: 'Step 01: Chassis',
    step01title: 'Core Specifications',
    step02: 'Step 02: Aesthetics',
    step02title: 'Dial & Furniture',
    step03: 'Step 03: Hardware',
    step03title: 'Bracelet & Clasp',
    serialNumber: 'Serial Number',
    referenceNumber: 'Reference Number',
    caliber: 'Caliber',
    dialMark: 'Dial Mark / Variant',
    casebackStamp: 'Caseback Stamping',
    braceletRef: 'Bracelet Reference',
    claspCode: 'Clasp Code',
    estProduction: 'Est. Production:',
    expected: 'Expected:',
    ruleEngine: 'Verification Engine Logic (15-Point Check)',
    certificate: 'Coevality Certificate',
    anomaly: 'ANOMALY',
    coherent: 'COERENTE',
    coherenceScore: 'Coherence Score',
    verdict: 'Verdict',
    anomalyDetected: 'ANOMALY DETECTED',
    anomalyFlags: 'Detailed Anomaly Flags',
    dbReference: 'Database Reference',
    benchmarks: 'Visual Coevality Benchmarks (Ref. 1675)',

    // AlertsPage
    surveillanceLabel: 'Market Surveillance',
    alertsTitle: 'Price Alerts',
    monitoringOnline: 'Monitoring Agents: Online',
    totalScanned: 'Total Scanned',
    listingsDay: '1.2M Listings/Day',
    createSurveillance: 'Create Surveillance',
    watchReferenceLabel: 'Watch Reference / Model',
    watchReferencePlaceholder: 'e.g. 116610LN',
    targetPriceLabel: 'Target Price Limit (€)',
    targetPricePlaceholder: '45000',
    targetPriceSub: 'Alert when price drops below target',
    emailNotification: 'Email notification',
    notificationChannels: 'Notification Channels',
    scanningSources: 'Scanning Sources',
    initializeAlert: 'Initialize Alert',
    initializingAlert: 'Initializing…',
    activeMonitored: 'Active Monitored Targets',
    slotAvailable: 'Slot Available',
    upgradeMore: 'Upgrade for more slots',
    scanFrequency: 'Scanning Frequency',
    every30min: 'Every 30 Minutes',
    avgResponse: 'Avg Response Time',
    responseTime: '1.4s (Global Edge)',
    alertEfficiency: 'Alert Efficiency',
    accuracy: '99.8% Accuracy',
    activeChannels: 'Active Channels',
    targetPrice: 'Target Price',
    checkEvery: 'Check Every',
    lastTriggered: 'Last Triggered',
    marketVolatility: 'Market Volatility Index',
    stableBuying: 'Stable Buying Zone',
    ref: 'Ref.',
    scanning: 'Scanning',
    targetHit: 'Target Hit',
    volatilityIndex: '0.84',

    // AuctionsPage
    auctionsNav: 'Auctions',
    auctionIntelligence: 'Auction Intelligence',
    auctionIntelligenceSub: 'Real-time tracking of major watch auction houses worldwide',
    nextAuction: 'Next Auction',
    liveNow: 'LIVE NOW',
    upcomingLabel: 'Upcoming',
    completedLabel: 'Completed',
    allHousesLabel: 'All Houses',
    estimateLabel: 'Estimate',
    hammerPriceLabel: 'Hammer Price',
    lotLabel: 'Lot',
    viewLotLabel: 'View Lot',
    trackLotLabel: 'Track',
    connectedSources: 'Connected Sources',
    lastUpdatedLabel: 'Last updated',
    featuredLotsLabel: 'Featured Lots',
    recordPricesLabel: 'Record Prices',
    saleLabel: 'Sale',
    lotsLabel: 'Lots',
    dayLabel: 'day',
    daysLabel: 'days',
    hoursLabel: 'h',
    minutesLabel: 'min',
    onlineLabel: 'Online',
    scrapingEvery: 'Polling every',
    scrapingLive: '30s during live sale',
    scrapingCalendar: '6h calendar sync',
    scrapingResults: '2h after sale close',
    sourceActive: 'Active',
    sourcePending: 'Pending',
    totalLots: 'Lots tracked',
    housesConnected: 'Houses connected',
  },

  it: {
    // Sidebar
    dashboard: 'Dashboard',
    marketFeed: 'Ricerca Orologio',
    portfolio: 'Enciclopedia',
    priceAlerts: 'Alert Prezzi',
    analytics: 'Analytics',
    upgradePro: 'Passa a Pro',
    support: 'Supporto',
    settings: 'Impostazioni',

    // TopBar
    searchPlaceholder: 'Cerca referenza...',
    marketIndexes: 'Indici Mercato',
    auctions: 'Aste',
    valuation: 'Valutazione',

    // HomePage
    watchWorldTitle: 'Mercato Orologi di Lusso',
    watchWorldSub: 'Panoramica globale — intelligence di mercato per collezionisti seri',
    marketHighlightsTitle: 'Highlights di Mercato',
    auctionCalendarTitle: 'Calendario Aste',
    auctionResultsTitle: 'Ultimi Risultati d\'Asta',
    auctionResultsSub: 'I maggiori prezzi martello dalle recenti vendite',
    topInvestmentTitle: 'Miglior Investimento',
    topInvestmentSub: 'Analisi degli ultimi 12 mesi',
    recentSearchesTitle: 'Ricerche Recenti',
    recentSearchesSub: 'Monitora l\'evoluzione dei prezzi sulle referenze seguite',
    viewAll: 'Vedi tutto',
    searchNow: 'Cerca ora',
    invest_score: 'Investment Score',
    invest_12m: 'Rendimento 12 mesi',
    invest_volume: 'Volume di mercato',
    invest_liquidity: 'Liquidità',
    auction_house: 'Casa d\'Asta',
    auction_date: 'Data',
    auction_location: 'Luogo',
    auction_lots: 'Lotti Principali',
    auction_hammer: 'Prezzo Martello',
    auction_estimate: 'Stima',
    auction_result: 'Risultato',
    noRecentSearches: 'Nessuna ricerca recente',
    noRecentSub: 'Avvia una scansione per costruire lo storico',
    priceUp: 'sopra la stima',
    priceAbove: 'vs stima',
    loading: 'Caricamento…',

    // SearchPage
    scanTerminal: 'Scan Terminal',
    marketIntelligence: 'Market Intelligence',
    referenceLabel: 'Referenza Orologio',
    referencePlaceholder: 'es. 116610LN · 5711/1A · 126710BLNR',
    maxPriceLabel: 'Prezzo max (€) — opzionale',
    maxPricePlaceholder: 'es. 12000',
    scanButton: 'Scansiona',
    scanningButton: 'Scansione…',
    quickSearch: 'Rapido:',
    scanFromPhoto: 'Cerca da foto',
    identifying: 'Identificazione…',
    scanningFor: 'Scansione per',
    agentsActive: 'Agenti paralleli attivi',
    scanDuration: 'La scansione richiede 40–60 secondi',
    scanDone: 'Fatto',
    resultsFound: 'RISULTATI TROVATI',
    liveMarketFeed: 'LIVE MARKET FEED',
    sortPrice: 'Ordina: Prezzo Crescente',
    priceRange: 'Fascia di Prezzo (€)',
    accessories: 'Accessori',
    location: 'Posizione',
    marketSource: 'Fonte di Mercato',
    worldwide: 'Globale',
    italy: 'Italia',
    europe: 'Europa',
    allAccessories: 'Tutti',
    boxPapers: 'Scatola e Garanzia',
    watchOnly: 'Solo Orologio',
    filterSeller: 'Filtra venditore…',
    viewDetails: 'Vedi Dettagli',
    contactSeller: 'Contatta Venditore',
    noResults: 'Nessun risultato con i filtri selezionati',
    noResultsSub: 'Cambia zona o filtro accessori',
    noListings: 'Nessuna offerta per',
    noListingsSub: 'Prova senza prezzo massimo o con una referenza diversa',
    bestPrice: 'Miglior Prezzo',
    topRanked: 'OFFERTA TOP',
    bestDeal: 'Miglior Affare',
    marketPrice: 'Prezzo di Mercato',
    socialVerified: 'Verificato Social',
    completedIn: 'Completato in',

    // VerificationPage
    coevTitle: 'Motore di Verifica Coevità',
    coevSub: 'Rigido rispetto delle regole archivistiche di coevità. Validazione di cassa, calibro e coerenza estetica.',
    saveAnalysis: 'Salva Analisi',
    exportPdf: 'Esporta PDF',
    step01: 'Passo 01: Cassa',
    step01title: 'Specifiche Principali',
    step02: 'Passo 02: Estetica',
    step02title: 'Quadrante e Componenti',
    step03: 'Passo 03: Hardware',
    step03title: 'Bracciale e Chiusura',
    serialNumber: 'Numero di Serie',
    referenceNumber: 'Numero di Referenza',
    caliber: 'Calibro',
    dialMark: 'Variante Quadrante',
    casebackStamp: 'Stampa Fondello',
    braceletRef: 'Referenza Bracciale',
    claspCode: 'Codice Chiusura',
    estProduction: 'Produzione Stimata:',
    expected: 'Atteso:',
    ruleEngine: 'Logica Motore (15 Verifiche)',
    certificate: 'Certificato Coevità',
    anomaly: 'ANOMALIA',
    coherent: 'COERENTE',
    coherenceScore: 'Punteggio Coerenza',
    verdict: 'Verdetto',
    anomalyDetected: 'ANOMALIA RILEVATA',
    anomalyFlags: 'Segnalazioni Anomalie',
    dbReference: 'Riferimento Database',
    benchmarks: 'Benchmark Visivi Coevità (Rif. 1675)',

    // AlertsPage
    surveillanceLabel: 'Sorveglianza Mercato',
    alertsTitle: 'Alert Prezzi',
    monitoringOnline: 'Agenti di Monitoraggio: Online',
    totalScanned: 'Scansioni Totali',
    listingsDay: '1.2M Annunci/Giorno',
    createSurveillance: 'Crea Sorveglianza',
    watchReferenceLabel: 'Referenza / Modello',
    watchReferencePlaceholder: 'es. 116610LN',
    targetPriceLabel: 'Limite Prezzo Target (€)',
    targetPricePlaceholder: '45000',
    targetPriceSub: 'Alert quando il prezzo scende sotto il target',
    emailNotification: 'Notifica email',
    notificationChannels: 'Canali di Notifica',
    scanningSources: 'Fonti di Scansione',
    initializeAlert: 'Attiva Alert',
    initializingAlert: 'Attivazione…',
    activeMonitored: 'Target Monitorati Attivi',
    slotAvailable: 'Slot Disponibile',
    upgradeMore: 'Fai upgrade per più slot',
    scanFrequency: 'Frequenza Scansione',
    every30min: 'Ogni 30 Minuti',
    avgResponse: 'Tempo di Risposta Medio',
    responseTime: '1.4s (Global Edge)',
    alertEfficiency: 'Efficienza Alert',
    accuracy: '99.8% Accuratezza',
    activeChannels: 'Canali Attivi',
    targetPrice: 'Prezzo Target',
    checkEvery: 'Controllo Ogni',
    lastTriggered: 'Ultima Attivazione',
    marketVolatility: 'Indice Volatilità Mercato',
    stableBuying: 'Zona di Acquisto Stabile',
    ref: 'Rif.',
    scanning: 'Scansione',
    targetHit: 'Target Raggiunto',
    volatilityIndex: '0.84',

    // AuctionsPage
    auctionsNav: 'Aste',
    auctionIntelligence: 'Intelligence Aste',
    auctionIntelligenceSub: 'Monitoraggio in tempo reale delle principali case d\'asta di orologi',
    nextAuction: 'Prossima Asta',
    liveNow: 'IN CORSO',
    upcomingLabel: 'In Programma',
    completedLabel: 'Concluse',
    allHousesLabel: 'Tutte le Case',
    estimateLabel: 'Stima',
    hammerPriceLabel: 'Prezzo Martello',
    lotLabel: 'Lotto',
    viewLotLabel: 'Vedi Lotto',
    trackLotLabel: 'Traccia',
    connectedSources: 'Fonti Collegate',
    lastUpdatedLabel: 'Aggiornato',
    featuredLotsLabel: 'Lotti in Evidenza',
    recordPricesLabel: 'Record di Vendita',
    saleLabel: 'Vendita',
    lotsLabel: 'Lotti',
    dayLabel: 'giorno',
    daysLabel: 'giorni',
    hoursLabel: 'h',
    minutesLabel: 'min',
    onlineLabel: 'Online',
    scrapingEvery: 'Polling ogni',
    scrapingLive: '30s durante la vendita live',
    scrapingCalendar: '6h sync calendario',
    scrapingResults: '2h dalla chiusura vendita',
    sourceActive: 'Attivo',
    sourcePending: 'In attesa',
    totalLots: 'Lotti monitorati',
    housesConnected: 'Case collegate',
  },
} as const

export type TKey = keyof typeof T.en
export type Translations = Record<TKey, string>

type LangContext = {
  lang: Lang
  setLang: (l: Lang) => void
  t: Translations
}

const LangCtx = createContext<LangContext>({
  lang: 'it',
  setLang: () => {},
  t: T.it as Translations,
})

export function LangProvider({ children }: { children: ReactNode }) {
  const stored = (typeof localStorage !== 'undefined' ? localStorage.getItem('lang') : null) as Lang | null
  const [lang, setLangState] = useState<Lang>(stored ?? 'it')

  const setLang = (l: Lang) => {
    localStorage.setItem('lang', l)
    setLangState(l)
  }

  return (
    <LangCtx.Provider value={{ lang, setLang, t: T[lang] as Translations }}>
      {children}
    </LangCtx.Provider>
  )
}

export function useLang() {
  return useContext(LangCtx)
}
